[GN-5030] Road sign concepts redesign
lblod/frontend-mow-registry pull request #284
Opened 2024-09-16 14:04 UTC by Windvis

2024-09-25 11:55 UTC, Windvis commented on app/templates/road-sign-concepts/index.hbs
> +            @disabled={{this.canResetFilters}}
The name is confusing, since you would expect the opposite. We need to give it a better name.

2024-09-25 12:30 UTC, andreo141 requested changes

2024-09-25 12:30 UTC, andreo141 commented on app/templates/road-sign-concepts/road-sign-concept/related.hbs
> +<AuBodyContainer @scroll={{true}} class="au-c-body-container--tables">
The scroll seems broken here, although you added `@scroll={{true}}`. I think the issue is in the SidebarOverlayContainer component. Try adding 
```css
.sidebar-overlay-container {
  overflow-y: scroll;
}
```

2024-09-26 07:48 UTC, andreo141 approved these changes
Looks good :100:

2024-09-26 08:04 UTC, merged